# Autogenerated wrapper script for libva_jll for armv6l-linux-gnueabihf
export libva, libva_drm, libva_x11

using libdrm_jll
using Xorg_libX11_jll
using Xorg_libXext_jll
using Xorg_libXfixes_jll
JLLWrappers.@generate_wrapper_header("libva")
JLLWrappers.@declare_library_product(libva, "libva.so.2")
JLLWrappers.@declare_library_product(libva_drm, "libva-drm.so.2")
JLLWrappers.@declare_library_product(libva_x11, "libva-x11.so.2")
function __init__()
    JLLWrappers.@generate_init_header(libdrm_jll, Xorg_libX11_jll, Xorg_libXext_jll, Xorg_libXfixes_jll)
    JLLWrappers.@init_library_product(
        libva,
        "lib/libva.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libva_drm,
        "lib/libva-drm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libva_x11,
        "lib/libva-x11.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
